=== Adelina-Trandafir/KBot/VERCON/REFERINTE/Rbb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Rbb" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Rbb">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="XnItL+GOyUCv8kWfFROOPg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1440"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="RjIq5+Mog0OerE2ydS4d4Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="N" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2472"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="tFxxeiQbKUicO4hIRqFKtA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="V" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="iU1vgG87bkSXp8X/gTirvQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="E" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="71rWnMtDOUid7Ysy0QWjNg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="T" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="XYfFgoGUx0qcXA4tC8HJkA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="C" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ONgENdwp9kylEu//wnWDAA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="M" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="9TovaUKSsE2LNQ44TPhOZg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Adelina-Trandafir/KBot/VERCON/REFERINTE/Rbb.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Rbb.xsd" generated="2026-10-11T17:56:35">
<Rbb>
<ID>1</ID>
<N>Tab_CFG</N>
<V>1</V>
<E>1</E>
<T>1</T>
</Rbb>
<Rbb>
<ID>2</ID>
<N>Tab_Gest</N>
<V>1</V>
<E>1</E>
<T>1</T>
</Rbb>
<Rbb>
<ID>3</ID>
<N>Tab_OI</N>
<V>1</V>
<E>1</E>
<T>1</T>
</Rbb>
<Rbb>
<ID>4</ID>
<N>Tab_MF</N>
<V>0</V>
<E>0</E>
<T>1</T>
</Rbb>
<Rbb>
<ID>5</ID>
<N>Tab_rap</N>
<V>1</V>
<E>1</E>
<T>1</T>
</Rbb>
<Rbb>
<ID>6</ID>
<N>btnAddProd</N>
<V>1</V>
<E>1</E>
<T>0</T>
<C>gest_CPV</C>
</Rbb>
<Rbb>
<ID>7</ID>
<N>btnCategorii</N>
<V>1</V>
<E>1</E>
<T>0</T>
<C>Masini</C>
</Rbb>
<Rbb>
<ID>8</ID>
<N>btnUnitate</N>
<V>1</V>
<E>1</E>
<T>0</T>
<C>Config</C>
</Rbb>
<Rbb>
<ID>9</ID>
<N>btnCoduri</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>10</ID>
<N>btnInchidere</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>11</ID>
<N>btnAddNIR</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>12</ID>
<N>btnDelNir</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>13</ID>
<N>btnAddBC</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>14</ID>
<N>btnDelBC</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>15</ID>
<N>btnAddLA</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>18</ID>
<N>btnLstSFP</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>19</ID>
<N>btnFurnizori</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>20</ID>
<N>btnClienti</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>21</ID>
<N>btnAddStorno</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>22</ID>
<N>btnAddBP</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>23</ID>
<N>btnAddBT</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>24</ID>
<N>btnAddBS</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>25</ID>
<N>grp0</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>26</ID>
<N>grp5</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>27</ID>
<N>grp2</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>28</ID>
<N>grp3</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>29</ID>
<N>grp6</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>30</ID>
<N>grp7</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>31</ID>
<N>grp4</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>32</ID>
<N>sep1</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>33</ID>
<N>sep2</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>34</ID>
<N>sep3</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>35</ID>
<N>sep4</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>36</ID>
<N>sep5</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>49</ID>
<N>ExportExcel</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>50</ID>
<N>FilePrintQuick</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>51</ID>
<N>FileSaveAsPdfOrXps</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>52</ID>
<N>GroupZoom</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>53</ID>
<N>grp0</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>54</ID>
<N>PageSetupDialog</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>55</ID>
<N>PrintPreviewClose</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>56</ID>
<N>sep4</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>57</ID>
<N>sep5</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>58</ID>
<N>sep8</N>
<V>1</V>
<E>1</E>
<T>0</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>59</ID>
<N>tabPPVW</N>
<V>1</V>
<E>1</E>
<T>1</T>
<M>PPVW</M>
</Rbb>
<Rbb>
<ID>60</ID>
<N>btnAmmy</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>61</ID>
<N>btnBCK</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>63</ID>
<N>btnUPDN</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
<Rbb>
<ID>64</ID>
<N>btnAddRe</N>
<V>1</V>
<E>1</E>
<T>0</T>
</Rbb>
</dataroot>
